Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,8 +32,14 @@ jobs:
         id: run_tests
         continue-on-error: true
         run: |
-          pytest || echo "::set-output name=result::1"
-          echo "::set-output name=result::0"
+          pytest --tb=short -q --disable-warnings
+          if [ $? -eq 0 ]; then
+            echo "Tests passed"
+            echo "::set-output name=result::0"
+          else
+            echo "Tests failed"
+            echo "::set-output name=result::1"
+          fi
 
   handle_failure:
     needs: test
